### ISSUE TITLE
"make clean" in rootdir halts if clean failed in any subdirectory

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage-skeleton#154]
I would expect "make clean" to continue attempting to make clean in other directories if an invocation of `ocamlbuild -clean` in one subdirectory fails.

**Comment by talex5** [comment]
Why is `ocamlbuild -clean` failing?

**Comment by yomimono** [comment]
Indeed that's a better way of stating the problem, now that I've caused it locally rather than reading it off someone else's screen.  Causing `config.ml` to not be interpretable results in this result from `make clean`, percolating up from `mirage clean -f console/config.ml`:

```
$ make clean
mirage clean -f console/config.ml
[ERROR]
  
ocamlfind ocamldep -package mirage -modules config.ml > config.ml.depends
+ ocamlfind ocamldep -package mirage -modules config.ml > config.ml.depends
File "config.ml", line 3, characters 0-1:
Error: Syntax error
Command exited with code 2.

Makefile:45: recipe for target 'console-clean' failed
make: *** [console-clean] Error 1
```

**Comment by mor1** [comment]
possible fix in #155 ?

**Comment by talex5** [comment]
Is there anything to fix then? If you ask it to clean and it can't because there's an error, then it should report the error and stop so you can fix it, right?

**Comment by mor1** [comment]
Well, I would tend to go with @yomimono expectation here, that `clean` is a
slightly special target that would just power on through any problems, as
it might be invoked to tidy up after things have got to an inconsistent
state due to said problems. Particularly for a target like this which is
iterating over multiple independent components. (A clear indication that
there is something that needs looking at in a failing directory would be
nice though.)

I'd certainly expect `configure` or `build` to stop when problems
encountered though.


On 13 July 2016 at 11:32, Thomas Leonard <notifications@github.com> wrote:

> Is there anything to fix then? If you ask it to clean and it can't because
> there's an error, then it should report the error and stop so you can fix
> it, right?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mirage/mirage-skeleton/issues/154#issuecomment-232318432>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAKP4NtqWfuhofs8PyjIw0w2CVzRmlZoks5qVL6-gaJpZM4JLQeW>
> .
>



-- 
Richard Mortier
mort@cantab.net
