### ISSUE TITLE
[Opam] dns -> uri < 1.9.4 unmet dependency

### ISSUE THREAD

**Issue by johann-sonntagbauer** [mirage/mirage-skeleton#231]
I am trying to setup the static website application but fail to install the dependencies with opam. Following the Readme instructions the problem occurs during `make prepend`. Following unmet dependency error is listed:

```
The following dependencies couldn't be met:
  - dns -> uri < 1.9.4
Your request can't be satisfied:
  - No package matches uri<1.9.4.
```
I have checked the dependencies for mirage-dns and found no upper version boundary like that. So why thinks opam that uri is only valid between (>= 1.7.0 & < 1.9.4) but the opam metadata only lists following version boundary  "uri" {>= "1.7.0"} 

Is there a way to ship around that problem?

Some stats:
ocaml: 4.03.0
opam: 1.2.2

**Comment by hannesm** [comment]
Thanks for the report, dns 0.20.* indeed conflicted with uri 1.9.4 (I'm not sure which opam metadata you looked at, opam uses the repository one from https://github.com/ocaml/opam-repository/tree/master/packages/dns).

Since the dns 1.0.0 release, newer uri versions are fine.  Please run `opam update` and `opam upgrade` to install newer versions, and report if the problem persists.
