### ISSUE TITLE
Tutorial seems (partly) broken [hello]

### ISSUE THREAD

**Issue by lwehmeier** [mirage/mirage-skeleton#252]
Problem: Can't configure tutorial/hello example by running mirage configure -t unix as described in the tutorial on mirage.io. Error message: mirage: unknown option `-t'

Reproduce:
1) Install dependencies according to getting started guide
2) Follow steps of the hello-world tutorial
2.1) Works fine for tutorial/noop 
2.2) Fails during tutorial/hello at mirage configure -t unix
2.3) Also fails for other arguments, e.g. -t ukvm

Test setup:
Ubutu 16.04 (on docker)
OCaml 4.02.3
Mirage 2.9.1

**Comment by hannesm** [comment]
thanks for your report, @lwehmeier.  since around a year, we have a mirage 3.0.0 release which had various breaking changes in there.  as mentioned in the README. md of this repository, `Please ensure that your Mirage command-line version is at least 3.0.0 before proceeding`. Mirage 2 is end of life.

To upgrade your setup:
- `opam switch 4.06.0` <- current MirageOS releases target OCaml 4.04.2 or higher
- `eval $(opam config env)`
- `opam install mirage` <- this should install you a 3.0.x version

**Comment by lwehmeier** [comment]
Ok, that fixed it. Sorry, must have missed that part in the installation instructions and never thought to read them again as the noop tutorial part seemed to work just fine.

Maybe consider adding a paragraph on this to the tutorial section for people like me who manage not to read the installation instructions carefully enough?;)

Thx
